name: Continuous Integration

on:
  push:

env:
  PLAYGROUND_API: ''
  AVATAAR_URL: ''
  GA_TRACKING_CODE: ''
  MIXPANEL_TOKEN: ''
  DEFAULT_SEO_IMAGE: ''
  SENTRY_DSN: ''

jobs:
  test:
    name: 'Tests'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: make ci
